version: "3.9"

networks:
  triercloud-net:
    external:
      name: triercloud-net

services:
  api-cep:
    container_name: "api-cep"
    image: convcard/api-cep:2.0.0
    networks:
      - triercloud-net
    ports:
      - "8585:8585"
    extra_hosts:
      - "local.triercloud.com.br:127.0.0.1"
    environment:
      SERVER_PORT: "8585"
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_DATA_MONGODB_HOST: "mongo"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "cep"
