version: "3.9"

networks:
  triercloud-net:
    external:
      name: triercloud-net

services:
  api-cep:
    container_name: "api-cep"
    image: convcard/api-cep:2.0.0
    networks:
      - triercloud-net
    ports:
      - "8585:8585"
    extra_hosts:
      - "local.triercloud.com.br:127.0.0.1"
    environment:
      SERVER_PORT: "8585"
      SPRING_PROFILES_ACTIVE: "qa"
      SPRING_R2DBC_URL: "r2dbc:postgresql://postgres:5432/cep"
      SPRING_R2DBC_USERNAME: "postgres"
      SPRING_R2DBC_PASSWORD: "postgres"
      SPRING_FLYWAY_URL: "jdbc:postgresql://postgres:5432/cep"
      SPRING_FLYWAY_USER: "postgres"
      SPRING_FLYWAY_PASSWORD: "postgres"
