version: "3.9"

networks:
  triercloud-net:
    external:
      name: triercloud-net

volumes:
  mongo_data:

services:
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - triercloud-net
