server:
  port: 8585
  error:
    include-message: always
    include-stacktrace: never
spring:
  profiles:
    default: local
  application:
    name: @project.name@
    version: @project.version@
  jackson:
    default-property-inclusion: always
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  webflux:
    base-path: /@project.name@
  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: true
      repositories:
        enabled: true
logging:
  file:
    name: logs/@project.name@.log
  logback:
    rollingpolicy:
      max-history: 1024
      max-file-size: 64MB
management:
  endpoint:
    health:
      probes:
        add-additional-paths: off
        enabled: true
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
cep:
  expiracao-cep-error-dias: 30
  ibge:
    habilitado: true
    ordem: -1
  cep-aberto:
    habilitado: true
    ordem: 0
    token: f0272ee35fe5718d3de24cec3f51b6d9
  open-street:
    habilitado: true
    ordem: 1
  via-cep:
    habilitado: true
    ordem: 2
  postmon:
    habilitado: true
    ordem: 3
  correios-api:
    habilitado: true
    ordem: 4
  correios-web:
    habilitado: true
    ordem: 5

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cep

logging:
  level:
    org.springframework: DEBUG
    db.migration: DEBUG
    br.com.github.victorhugoof: DEBUG
debug: true

---
spring:
  config:
    activate:
      on-profile: qa
  data:
    mongodb:
      host: 192.168.150.246
      port: 27017
      database: cep

---
spring:
  config:
    activate:
      on-profile: producao
  data:
    mongodb:
      host: 172.30.212.136
      port: 27017
      database: cep
