server:
  port: 8585
  error:
    include-message: always
    include-stacktrace: never
spring:
  profiles:
    default: local
  application:
    name: @project.name@
    version: @project.version@
  jackson:
    default-property-inclusion: always
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  flyway:
    enabled: true
    fail-on-missing-locations: true
  webflux:
    base-path: /@project.name@
logging:
  file:
    name: logs/@project.name@.log
  logback:
    rollingpolicy:
      max-history: 1024
      max-file-size: 64MB
management:
  endpoint:
    health:
      probes:
        add-additional-paths: off
        enabled: true
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
cep:
  expiracao-cep-error-dias: 30
  ibge:
    habilitado: true
    ordem: -1
  cep-aberto:
    habilitado: true
    ordem: 0
    token: f0272ee35fe5718d3de24cec3f51b6d9
  open-street:
    habilitado: true
    ordem: 1
  via-cep:
    habilitado: true
    ordem: 2
  postmon:
    habilitado: true
    ordem: 3
  correios-api:
    habilitado: true
    ordem: 4
  correios-web:
    habilitado: true
    ordem: 5

---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cep
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/cep
    user: postgres
    password: postgres
  config:
    activate:
      on-profile: local
logging:
  level:
    org.springframework: DEBUG
debug: true

---
spring:
  r2dbc:
    url: r2dbc:postgresql://192.168.150.246:5432/cep
    username: pod1
    password: pod1
  flyway:
    url: jdbc:postgresql://192.168.150.246:5432/cep
    user: pod1
    password: pod1
  config:
    activate:
      on-profile: qa

---
spring:
  r2dbc:
    url: r2dbc:postgresql://172.30.212.136:5432/cep
    username: pod1
    password: pod1
  flyway:
    url: jdbc:postgresql://172.30.212.136:5432/cep
    user: pod1
    password: pod1
  config:
    activate:
      on-profile: producao
