ALTER TABLE cep ADD created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE cep ADD updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE cep_error ADD created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE cep_error ADD updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE cidade ADD created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE cidade ADD updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
